apiVersion: v1
kind: Deployment
metadata:
  name: debug
  namespace: roboshop
  labels:
    name: debug
    project: roboshop
spec:
  replicas: 1
  selector:
    matchLabels:
      name: debug
      project: roboshop
  template:
    metadata:
      labels:
        name: debug
        project: roboshop
    spec:  
      containers:
      - name: debug
        image: venkatesh990/debug:v1
        imagePullPolicy: Always